# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "27593f2c-5eaf-4ae7-90d5-e51949c286db",
# META       "default_lakehouse_name": "ChicagoPublicSafety",
# META       "default_lakehouse_workspace_id": "18c93f05-44a2-4a59-8a64-785ccdbd7725",
# META       "known_lakehouses": [
# META         {
# META           "id": "27593f2c-5eaf-4ae7-90d5-e51949c286db"
# META         }
# META       ]
# META     }
# META   }
# META }

# MARKDOWN ********************

# 
# #### Run the cell below to install the required packages for Copilot


# CELL ********************


#Run this cell to install the required packages for Copilot
#%pip install https://aka.ms/chat_magics-0.0.0-py3-none-any.whl
#%load_ext chat_magics


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# This notebook connects to the latest data uploaded to the bronze layer in the OneLake (which is a parquet file), creates DataFrame from it, and then executes some transform code to change data types and drop columns. Then it writes to the Delta Table

# PARAMETERS CELL ********************

#This is a parameter cell, the default value here will be replaced when this notebook is invoked by a pipeline
#RunID = "ed490741-c162-4a8b-b500-c4abf98fe400_LastFull"
RunID = "ae2450d2-d315-437c-8e84-b36a48b41edb"

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

#The Bronze Layer in the OneLake consists of folders that represent the latest run of the ingest pipeline. That pipeline connects to the
# City of Chicago SODA endpoint, constructs a query, and returns the newest records and then writes them to a parquet file using the name
# constructed from the pipeline RunID
FilePath = "Files/Bronze/LatestReports/"+RunID
#FilePath = "Files/Bronze/LatestReports/a0274d00-9cd6-45be-b1d8-e02d70ca3df0"
PoliceReports = spark.read.parquet(FilePath)
#PoliceReports = spark.read.parquet("abfss://FabricWorkspace@onelake.dfs.fabric.microsoft.com/ChicagoPublicSafety.Lakehouse/Files/Bronze/LatestReports/a0274d00-9cd6-45be-b1d8-e02d70ca3df0") 
#display(PoliceReports)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for PySpark DataFrame

from pyspark.sql import functions as F

def clean_data(PoliceReports):
    # Convert text to lowercase in column: 'case_number'
    PoliceReports = PoliceReports.withColumn('case_number', F.lower(F.col('case_number')))
    return PoliceReports

PoliceReports_clean = clean_data(PoliceReports)
#display(PoliceReports_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# This is code that was generated by Data Wrangler that performs various "Power Query" functions on the DataFrame

from pyspark.sql import types as T

def clean_data(PoliceReports):
    # Change column type to int64 for column: 'id'
    PoliceReports = PoliceReports.withColumn('id', PoliceReports['id'].cast(T.LongType()))
    # Change column type to datetime64[ns] for column: 'date'
    PoliceReports = PoliceReports.withColumn('date', PoliceReports['date'].cast(T.TimestampType()))
    # Replace NULL CommunityArea values with "0"
    PoliceReports = PoliceReports.fillna(value="0", subset=['community_area'])
    # Change column type to int32 for column: 'community_area'
    PoliceReports = PoliceReports.withColumn('community_area', PoliceReports['community_area'].cast(T.IntegerType()))
    # Drop column: 'x_coordinate'
    PoliceReports = PoliceReports.drop('x_coordinate')
    # Drop column: 'y_coordinate'
    PoliceReports = PoliceReports.drop('y_coordinate')
    # Change column type to int32 for column: 'year'
    PoliceReports = PoliceReports.withColumn('year', PoliceReports['year'].cast(T.IntegerType()))
    # Change column type to datetime64[ns] for column: 'updated_on'
    PoliceReports = PoliceReports.withColumn('updated_on', PoliceReports['updated_on'].cast(T.TimestampType()))
    # Change column type to float64 for column: 'latitude'
    PoliceReports = PoliceReports.withColumn('latitude', PoliceReports['latitude'].cast(T.DoubleType()))
    # Change column type to float64 for column: 'longitude'
    PoliceReports = PoliceReports.withColumn('longitude', PoliceReports['longitude'].cast(T.DoubleType()))
    # Drop column: 'human_address'
    PoliceReports = PoliceReports.drop('location.human_address')
    # Drop column: ':@computed_region_awaf_s7ux'
    PoliceReports = PoliceReports.drop(':@computed_region_awaf_s7ux')
    # Drop column: ':@computed_region_6mkv_f3dw'
    PoliceReports = PoliceReports.drop(':@computed_region_6mkv_f3dw')
    # Drop column: ':@computed_region_vrxf_vc4k'
    PoliceReports = PoliceReports.drop(':@computed_region_vrxf_vc4k')
    # Drop column: ':@computed_region_bdys_3d7i'
    PoliceReports = PoliceReports.drop(':@computed_region_bdys_3d7i')
    # Drop column: ':@computed_region_43wa_7qmu'
    PoliceReports = PoliceReports.drop(':@computed_region_43wa_7qmu')
    # Drop column: ':@computed_region_rpca_8um6'
    PoliceReports = PoliceReports.drop(':@computed_region_rpca_8um6')
    # Drop column: ':@computed_region_d9mm_jgwp'
    PoliceReports = PoliceReports.drop(':@computed_region_d9mm_jgwp')
    # Drop column: ':@computed_region_d3ds_rm58'
    PoliceReports = PoliceReports.drop(':@computed_region_d3ds_rm58')
    return PoliceReports

PoliceReports_clean = clean_data(PoliceReports)
#display(PoliceReports_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# This is also code generated by Data Wrangler. The reason I chose to break it into 2 cells is that there were some handline issues
# with columns that included a dot in the name, so I broke them out here to deal with them

from pyspark.sql import types as T

def clean_data(PoliceReports_clean):
    # Create a "Date Only" column to be used to join to the date dimension
    PoliceReports_clean = PoliceReports_clean.withColumn('dateonly',PoliceReports_clean['date'].cast(T.DateType()))
    return PoliceReports_clean

PoliceReports_clean_1 = clean_data(PoliceReports_clean)
#display(PoliceReports_clean_1)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Proper Case all of the column names so that they will appear nicely in reports
# Code generated by Data Wrangler for PySpark DataFrame

def clean_data(PoliceReports_clean_1):
    # Rename column 'case_number' to 'CaseNumber'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('case_number', 'CaseNumber')
    # Rename column 'date' to 'Date'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('date', 'Date')
    # Rename column 'block' to 'Block'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('block', 'Block')
    # Rename column 'community_area' to 'CommunityArea'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('community_area', 'CommunityArea')
    # Rename column 'iucr' to 'IUCR'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('iucr', 'IUCR')
    # Rename column 'primary_type' to 'PrimaryType'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('primary_type', 'PrimaryType')
    # Rename column 'description' to 'Description'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('description', 'Description')
    # Rename column 'location_description' to 'LocationDescription'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('location_description', 'LocationDescription')
    # Rename column 'arrest' to 'Arrest'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('arrest', 'Arrest')
    # Rename column 'domestic' to 'Domestic'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('domestic', 'Domestic')
    # Rename column 'beat' to 'Beat'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('beat', 'Beat')
    # Rename column 'district' to 'District'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('district', 'District')
    # Rename column 'fbi_code' to 'FBICode'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('fbi_code', 'FBICode')
    # Rename column 'updated_on' to 'LastUpdated'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('updated_on', 'LastUpdated')
    # Rename column 'latitude' to 'Latitude'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('latitude', 'Latitude')
    # Rename column 'longitude' to 'Longitude'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('longitude', 'Longitude')
    # Rename column 'location' to 'Location'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('location', 'Location')
    # Rename column 'dateonly' to 'DateOnly'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('dateonly', 'DateOnly')
    # Rename column 'ward' to 'Ward'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('ward', 'Ward')
    # Rename column 'year' to 'Year'
    PoliceReports_clean_1 = PoliceReports_clean_1.withColumnRenamed('year', 'Year')
    return PoliceReports_clean_1

PoliceReports_clean_2 = clean_data(PoliceReports_clean_1)
#display(PoliceReports_clean_2)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

#This will write to the Gold Layer with Vorder indexing to ensure performance with DirectLake in Power BI
spark.conf.set('spark.sql.parquet.vorder.enabled', 'true')
PoliceReports_clean_2.write.mode("append").format("delta").saveAsTable("ChicagoReports")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
