# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "2e441466-3a59-441e-b145-2f2a191204f3",
# META       "default_lakehouse_name": "temaloLakeHouse",
# META       "default_lakehouse_workspace_id": "b0c07f86-8a8f-4e0f-986b-6f6cb4660920",
# META       "known_lakehouses": [
# META         {
# META           "id": "2e441466-3a59-441e-b145-2f2a191204f3"
# META         }
# META       ]
# META     }
# META   }
# META }

# CELL ********************

iucrCodes = spark.read.format("csv").option("header","true").load("Files/DimensionData/Chicago_Police_Department_-_Illinois_Uniform_Crime_Reporting__IUCR__Codes.csv")
#display(iucrCodes)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for PySpark DataFrame

def clean_data(iucrCodes):
    # Rename column 'PRIMARY DESCRIPTION' to 'PrimaryDescription'
    iucrCodes = iucrCodes.withColumnRenamed('PRIMARY DESCRIPTION', 'PrimaryDescription')
    # Rename column 'SECONDARY DESCRIPTION' to 'SecondaryDescription'
    iucrCodes = iucrCodes.withColumnRenamed('SECONDARY DESCRIPTION', 'SecondaryDescription')
    # Rename column 'INDEX CODE' to 'IndexCode'
    iucrCodes = iucrCodes.withColumnRenamed('INDEX CODE', 'IndexCode')
    # Rename column 'ACTIVE' to 'Active'
    iucrCodes = iucrCodes.withColumnRenamed('ACTIVE', 'Active')
    return iucrCodes

iucrCodes_clean = clean_data(iucrCodes)
display(iucrCodes_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

spark.conf.set('spark.sql.parquet.vorder.enabled', 'true')
iucrCodes_clean.write.mode("overwrite").format("delta").saveAsTable("IUCRCodes")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

policeDistricts = spark.read.format("csv").option("header","true").load("Files/DimensionData/PoliceDistrictDec2012.csv")
# df now is a Spark DataFrame containing CSV data from "Files/DimensionData/PoliceDistrictDec2012.csv".
#display(policeDistricts)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************


# CELL ********************

spark.conf.set('spark.sql.parquet.vorder.enabled', 'true')
policeDistricts.write.mode("append").format("delta").saveAsTable("PoliceDistricts")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

policeStations = spark.read.format("csv").option("header","true").load("Files/DimensionData/Police_Stations.csv")
# df now is a Spark DataFrame containing CSV data from "Files/DimensionData/Police_Stations.csv".
#display(policeStations)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for PySpark DataFrame

from pyspark.sql import types as T

def clean_data(policeStations):
    # Drop rows with missing data in column: 'ADDRESS'
    policeStations = policeStations.dropna(subset=['ADDRESS'])
    # Rename column 'DISTRICT NAME' to 'DistrictName'
    policeStations = policeStations.withColumnRenamed('DISTRICT NAME', 'DistrictName')
    # Drop column: 'X COORDINATE'
    policeStations = policeStations.drop('X COORDINATE')
    # Drop column: 'Y COORDINATE'
    policeStations = policeStations.drop('Y COORDINATE')
    # Drop column: 'LOCATION'
    policeStations = policeStations.drop('LOCATION')
    # Change column type to float64 for column: 'LATITUDE'
    policeStations = policeStations.withColumn('LATITUDE', policeStations['LATITUDE'].cast(T.DoubleType()))
    # Change column type to float64 for column: 'LONGITUDE'
    policeStations = policeStations.withColumn('LONGITUDE', policeStations['LONGITUDE'].cast(T.DoubleType()))
    # Change column type to float64 for column: 'ZIP'
    policeStations = policeStations.withColumn('ZIP', policeStations['ZIP'].cast(T.DoubleType()))
    return policeStations

policeStations_clean = clean_data(policeStations)
display(policeStations_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

spark.conf.set('spark.sql.parquet.vorder.enabled', 'true')
policeStations_clean.write.mode("overwrite").format("delta").saveAsTable("PoliceStations")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

communityArea = spark.read.format("csv").option("header","false").load("Files/DimensionData/Community.csv")
#display(communityArea)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

def clean_data(communityArea):
    communityArea = communityArea.withColumnRenamed("_c0","CommunityId")
    communityArea = communityArea.withColumnRenamed("_c1","CommunityName")
    communityArea = communityArea.withColumnRenamed("_c2","CommunityArea")
    communityArea = communityArea.withColumnRenamed("_c3","CommunityLocation")
    communityArea = communityArea.drop("_c4")
    communityArea = communityArea.withColumnRenamed("_c5","WeatherStation")
    return(communityArea)
communityArea_clean = clean_data(communityArea) 
display(communityArea_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

spark.conf.set('spark.sql.parquet.vorder.enabled', 'true')
communityArea_clean.write.mode("overwrite").format("delta").saveAsTable("CommunityArea")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
